### ISSUE TITLE
SSH repositories fail to configure with coder

### ISSUE THREAD

**Issue by geiseri** [coder/envbuilder#31]
If I try to use a private git repository over SSH I see the following error:

```
envbuilder - Build development environments from repositories in a container
#1: 📦 Cloning ssh://git@github.com/hive-io/hive-rest.git to /workspaces/hive-rest.git...
Failed to clone repository: clone "ssh://git@github.com/hive-io/hive-rest.git": error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
Falling back to the default image...
#2: 🏗️ Building image...
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
#2: Retrieving image codercom/enterprise-base:ubuntu from registry index.docker.io
#2: Built cross stage deps: map[]
```

I didn't see a way to configure that to use the built in SSH key provided by coder.  Is there a missing setting?

**Comment by janLo** [comment]
Would it be sufficient to drop an coder agent binary into the envbuilder image and set `GIT_SSH_COMMAND=/.envbuilder/coder gitssh --` ?

**Comment by chrisspalm** [comment]
This would be useful!

**Comment by geiseri** [comment]
Those are in the user profile right?

**Comment by chewbh** [comment]
Is there plan to look at implementing this? Support for cloning over SSH in envbuilder will be very useful. 

Some developers has preference using SSH over HTTP/S for interacting with git. To them, it is not expected that a devcontainer workspace fail to build due to this, given that they have already configure a SSH key within Coder and that they are force to fallback to use HTTP/S for cloning. 

In addition, to support cloning private repos, we specifically need to add additional terraform logic or uses coder_external_auth  to configure GIT environment variables in the workspace template.

**Comment by nwrkbiz** [comment]
Adding support for this, would also provide a simple and secure workaround for #60

**Comment by thattolleyguy** [comment]
+1 for adding support for this. This is the #1 reason our company isn't using coder yet

**Comment by johnstcn** [comment]
Plan:
- Add support for reading a SSH private key from a file (SSH_KEY_PATH)
- Add support for passing in a known_hosts file (SSH_KNOWN_HOSTS_BASE64)
- Add support for performing a SSH keyscan and generating a known_hosts file if no known_hosts file provided
- Add support for SSH key authentication using SSH_KEY_PATH
- Add support for fetching an SSH key from Coder if CODER_AGENT_URL and CODER_AGENT_TOKEN are provided using coder/agentsdk and no SSH_KEY_PATH is provided.

**Comment by johnstcn** [comment]
Closing this issue out. A [follow-up issue](https://github.com/coder/terraform-provider-coder/issues/219) will provide the capability for the Coder terraform provider to inject the user's SSH private key into workspace resources. However, there should be no further changes required in envbuilder to support this.
