### ISSUE TITLE
Allow passing Git SSH key as an environment variable

### ISSUE THREAD

**Issue by phorcys420** [coder/envbuilder#333]
Following up to a [discord conversation](https://discord.com/channels/747933592273027093/971231372373033030/1279228570295599114) where an user tries to clone a Git repository via SSH and is met with the following error:
```
envbuilder v1.0.0-rc.6+23d086e - Build development environments from repositories in a container
coder/coder#1: 🔑 Using SSH authentication!
coder/coder#1: 🔑 No SSH key found, falling back to agent!
coder/coder#1: ❌ Failed to connect to SSH agent: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
coder/coder#1: 📦 Cloning git@github.com:XXX.git to /workspaces/XXX...
Failed to clone repository: clone "git@XXX.git": error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"

Falling back to the default image...
```

This makes sense because the Coder user's SSH key was never added to the workspace.

While there is a workaround, it's really not great, how can we make this better?
With k8s the issue is not that bad since you can just define a secret from the key and pass that secret as a file to the container, but what about Docker and VMs?

## Workaround
[Downloading the key](https://github.com/coder/modules/blob/main/git-commit-signing%2Frun.sh#L18-L36) to some temporary path (via an entrypoint script, since envbox runs before the agent)
(or via the TF provider's [`coder_workspace_owner.ssh_*`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace_owner#read-only) instead of using a script)
Then passing the key's path to `ENVBUILDER_GIT_SSH_PRIVATE_KEY_PATH`.

**Comment by 2o1o0** [comment]
Hey,
Not sure I'm using the right issue or if I should create a new one, but I ended up here after following [this](https://github.com/coder/envbuilder/pull/174) and [this](https://github.com/coder/terraform-provider-coder/issues/219).

So I'm trying to spin up some workspaces in K8S using some .devcontainers on a remote public gitlab repository that require authentication. As of now, I'd like to use the ssh key provided to the user within his profile to access this repository. In my case my Coder instance is setup to use OIDC from a local Keycloak instance.

My understanding is that envbuilder [can do this](https://github.com/coder/envbuilder/blob/main/docs/git-auth.md), if you provide a path to private key file or use SSH_AUTH_SOCK. And I'm suppose to use the first option in a Kubernetes context.
However, because its a file that is expected, am I suppose to create a new kubernetes secret from my template that would get details from `coder_workspace_owner.private_ssh_key` ?

I've tried to do exactly this modifying the default .devcontainer template for K8S to retrieve the owner private key to generate a secret and mount it as a file for envbuilder to use. However, by default the RBAC role cannot create new secret in the coder namespace. 

Am I missing something here or is it the current way to go and I need to grant more rights to my role?

Thanks!

**Comment by johnstcn** [comment]
> Am I missing something here or is it the current way to go and I need to grant more rights to my role? 

That's correct. If you're using the Helm chart, you can add the required roles and roleBindings to `extraTemplates` in your `values.yaml`.

> Also, this sounds like a workaround as it makes the users ssh key appear in my K8S "secrets"

Correct, this issue would be the actual fix!

**Comment by johnstcn** [comment]
Created a follow-up issue for the provider: https://github.com/coder/terraform-provider-envbuilder/issues/58

**Comment by mwiede** [comment]
stumbling in here and got it running with
`"ENVBUILDER_GIT_SSH_PRIVATE_KEY_BASE64": base64encode(data.coder_workspace_owner.me.ssh_private_key)`
