### ISSUE TITLE
clone via branch does not create a project dir

### ISSUE THREAD

**Issue by ericpaulsen** [coder/envbuilder#380]
from a prospective customer:

> when creating a devcontainer workspace via a direct repo link (e.g. https://github.com/org/repo-name), the envbuilder clones the repo into the `repo-name` directory, so you get `/workspaces/repo-name/`… , but when creating via a branch link (e.g. https://github.com/org/repo-name/#refs/heads/jon-coder), the envbuilder seems to clone the repo contents directly into `workspaces`, so you get `/workspaces/`…

this is blocking their devcontainer use-case with Coder, because their build/service scripts rely on the source path in order to work, so the project not being in `/workspaces/repo-name/` is breaking the services.

**Comment by mafredri** [comment]
@ericpaulsen I'm trying to reproduce this with envbuilder 1.0 but it seems to work as expected. Could you provide the following additional information:

- Envbuilder version
- Exact Git URL format (e.g. `https://[redacted].git#refs/heads/...`)
- Whether or not `ENVBUILDER_WORKSPACE_FOLDER` is set and to which value

**Comment by JonathanSun** [comment]
I believe it’s a bug in this code:
https://github.com/coder/envbuilder/blob/46c97a46b96f3ca12f9718766b7eb610e0f1e80d/options/defaults.go#L20
I’m able to reproduce by testing the code locally on an input like `https://github.com/[org]/[repo]/#refs/heads/[branch]`

Specifically this line:
https://github.com/coder/envbuilder/blob/46c97a46b96f3ca12f9718766b7eb610e0f1e80d/options/defaults.go#L28

For the URL `https://github.com/[org]/[repo]/#refs/heads/[branch]`, this results in `name`:
`["", "[org]", "[repo]", ""]`
and the last argument (`""`) is chosen as the repo name instead of the proper name.

The same issue can be noticed by adding an extra `/` to any non-branch URL, i.e. `https://github.com/[org]/[repo]/`.  Also note that it doesn't matter whether `.git` is added to the repo identifier or not.

**Comment by ericpaulsen** [comment]
@JonathanSun @mafredri i am also able to reproduce:

i just reproduced this on dev.coder.com using the `Devcontainers` template and the following URL:

```
https://github.com/coder/coder/#refs/heads/cred-helper
```

no `ENVBUILDER_*` environment variables are set in the template. here's my `GIT_*` vars:

```console
$ env | grep GIT
GIT_SSH_COMMAND=/tmp/coder.vPtbyP/coder gitssh --
GIT_COMMITTER_NAME=eric
GIT_ASKPASS=/tmp/coder.vPtbyP/coder
GIT_AUTHOR_EMAIL=ericpaulsen@coder.com
GIT_COMMITTER_EMAIL=ericpaulsen@coder.com
GIT_AUTHOR_NAME=eric
```

**Comment by mafredri** [comment]
Thanks @JonathanSun for your investigation and @ericpaulsen for verification, I can also reproduce this by adding the trailing slash 👍🏻
