### ISSUE TITLE
Allow mounting in DOCKER_CONFIG again

### ISSUE THREAD

**Issue by johnstcn** [coder/envbuilder#392]
# Motivation

In https://github.com/coder/envbuilder/pull/336 we temporarily override `DOCKER_CONFIG` to set the config specified by `ENVBUILDER_DOCKER_CONFIG_BASE64`. 

This breaks some existing users who were mounting in a docker config and specifying the `DOCKER_CONFIG` environment variable in their image.

# Proposed solution

Only override `DOCKER_CONFIG` if `ENVBUILDER_DOCKER_CONFIG_BASE64` is set. Otherwise, leave it as-is.

**Comment by johnstcn** [comment]
Ah, good point. The difference in behaviour was pointed out between v1.0.0-rc.6 and v1.0.0-rc.7.

**Comment by mafredri** [comment]
Ok, so in v1.0.0-rc.7 the behavior was changed so that if you don't set base64, `DOCKER_CONFIG` doesn't get set either. Meaning if you define `DOCKER_CONFIG`, that's the one that will be used. However, if you were relying on envbuilder to search for a Docker config at `/.envbuilder/config.json`, then v1.0.0-rc.7 would break your use-case. Could this be what's happening?

**Comment by johnstcn** [comment]
Confirmed that this is what's happening.
